### PR TITLE
add support for late binding functions

### PR DESCRIPTION
**Pull request by duongchienthang**
usecase: logger.log( expensiveFunction.bind(x, y, z) )
detail:
http://blog.dcthang.net/2015/01/lazy-binding-for-logging-in-javascript.h
tml

### CODE REVIEW

**Comment by duongchienthang** [comment]
This is my very first time collaborate on GitHub. Please excuse my roughness.

**Comment by duongchienthang** [comment]
Am I supposed to close a pull request by myself? When should a pull request be closed?

**Comment by jonnyreeves** [comment]
Hi @duongchienthang, thanks for raising your first pull request.

Could you please explain these commits to me?  Unless I misunderstand, does the code:

```
logger.log( expensiveFunction.bind(x, y, z) )
```

result in a bound function being passed to the log method?  As far as I know, nothing will actually invoke that function so the log message will be `[Function function]` (or the source of the function depending on the runtime).

**Comment by duongchienthang** [comment]
It returns a bound function to be executed in the merge function. However the merge function is not called until the log level is checked. This guarantees that the expensive function will only be evaluated as needed.


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: John Reeves <notifications@github.com> </div><div>Date:01/30/2015  2:11 AM  (GMT-05:00) </div><div>To: jonnyreeves/js-logger <js-logger@noreply.github.com> </div><div>Cc: duongchienthang <dcthang@gmail.com> </div><div>Subject: Re: [js-logger] add support for late binding functions (#14) </div><div>
</div>Hi @duongchienthang, thanks for raising your first pull request.

Could you please explain these commits to me? Unless I misunderstand, does the code:

logger.log( expensiveFunction.bind(x, y, z) )
result in a bound function being passed to the log method? As far as I know, nothing will actually invoke that function so the log message will be [Function function] (or the source of the function depending on the runtime).

**Pull request closed without merging**
