### PR TITLE
Better-ify with noop.

### PR DESCRIPTION
**Pull request by donavon**
So let's say that you set your level to `ERROR`. That's fine, except all calls to `logger.warn` (for example) have to go through:
1. A call to `logger.invoke`
2. An `if` statement that does..
3. A call to `logger.enabledFor`.

That's a lot of work just to be told "no". My approach would set `logger.warn` (and the others) to a `noop` (no operation) function right in `logger.setLevel`.

My change is fully backwards compatible.

### CODE REVIEW

**Comment by begizi** [comment]
+1 to rebase and merge this.

**Comment by jonnyreeves** [comment]
Needs a rebase, I may be able to get around to it this month but if someone else wants to take the lead I would be greatful :+1:

**Comment by MidnightWonderer** [comment]
Hi,
I attempted to rebase it for you.
However, the rebasing is not complete because after I look closely into the code I decide to move on.
(Don't worry it is not that bad. I'm sure the old me will do something alike but after sometime you will understand.)
I will keep WIP rebasing branch on my repo all conflicts resolved but no functionality integration between 2 branches added.
  
Here the comparison
before rebase:
https://github.com/jonnyreeves/js-logger/pull/6/files?w=1
after rebase:
https://github.com/jonnyreeves/js-logger/compare/master...MidnightWonderer:better-ify-noop?w=1

If you want to merge the code you can use mine as starting point.

**Comment by jonnyreeves** [comment]
Abandoning this one :)

**Pull request closed without merging**
