### PR TITLE
update to stop objects being stringified before output to console.

### PR DESCRIPTION
**Pull request by paulinthought**
Adding the context.name + "]" + messages[0] was causing output in the console which looked like 
[MyContextualLogger] [object Object] 
This fix ensures that the object is viewable in the console

### CODE REVIEW

**Comment by jonnyreeves** [comment]
Are you sure that all browsers (so IE7 ;) support variadic arguments?

**Comment by paulinthought** [comment]
So, I've added a fix for the impacting change on the time and timeEnd methods.
I'm not sure I fully understand your IE7 comment. Is there somewhere else in the code that will be impacted by the unshift on the arguments?

**Comment by jonnyreeves** [comment]
I am not sure if IE7 (or other browsers for that matter) support more than
one argument being supplied to console.log (and friends) - if they do not,
then only the first argument (the logger's name) will be shown.

I am happy for this change to land if you are sure there is no impact.

**Comment by paulinthought** [comment]
I can't say about IE7 definitely though I expect it is pretty basic. I can see here on IE9 in IE7 emulation and IE9 mode that the output for console.log('a', {foo: 'bar'}); outputs a[objectObject] anyway and seems to require console.dir() to get a proper look into the object which defeats the purpose of the fix in IE anyway.
Chrome:
console.log('a' + {foo: 'bar'}) // a[object Object]
console.log('a', {foo: 'bar'}) // a Object {foo: "bar"}

IE:
console.log('a' + {foo: 'bar'}) // a[object Object]
console.log('a', {foo: 'bar'}) // a [object Object]

**Comment by jonnyreeves** [comment]
Rock on, this looks good to me - I'll look to merge it later this week
along with a minor version bump just in-case it has any un-intended
side-effects in the wild.

Thanks for contributing.

**Comment by paulinthought** [comment]
That's great. Thanks.

**Comment by jonnyreeves** [comment]
Merged in 1.1.0 - thanks again.

**Pull request closed without merging**
