### PR TITLE
Rename useDefaults to setDefaults.

### PR DESCRIPTION
**Pull request by harrisrobin**
using useDefaults breaks react-hooks/rules-of-hooks. This PR simply renames it to the more appropriate name `setDefaults` in order to avoid this issue.

Screen shot from a fresh CRA project when using `useDefaults`
👇 

image

### CODE REVIEW

**Comment by jonnyreeves** [comment]
Hi @harrisrobin, thank you for contributing back to this project.

Please could you revisit your diff and revert all the formatting changes as they are making your change difficult to review in isolation.

Also, as some premptive feedback, I am unlikely to accept a breaking change to the API given the maturity of this project, however this could easily be circumvented by introducing an alias to the old method name if you have not already done so.

**Comment by harrisrobin** [comment]
> Hi @harrisrobin, thank you for contributing back to this project.
> 
> Please could you revisit your diff and revert all the formatting changes as they are making your change difficult to review in isolation.
> 
> Also, as some premptive feedback, I am unlikely to accept a breaking change to the API given the maturity of this project, however this could easily be circumvented by introducing an alias to the old method name if you have not already done so.

That's a good idea. Will do, my bad that's my prettier config.

I can add an alias and undo the formatting changes 👍

**Comment by harrisrobin** [comment]
@jonnyreeves can you take a look now?

cheers 🍻

**Comment by jonnyreeves** [comment]
Lgtm. Will merge now but won't be able to release until tomorrow morning.

Thanks again for contributing

**Comment by jonnyreeves** [comment]
@harrisrobin fyi, I just published 1.6.1 which includes this new alias.

**Pull request merged**
