### PR TITLE
Added debug handler

### PR DESCRIPTION
**Pull request by ajwagner777**
Debug handler was missing.  Added it in so that debug messages get logged to console correctly.

### CODE REVIEW

**Comment by ajwagner777** [comment]
I see now that the tests failed.  Would you be opposed to changing the assertion like so: `assert.ok(console.debug.calledOnce, "logger.debug calls console.debug");`

**Comment by jonnyreeves** [comment]
Thanks for the pull @ajwagner777, your change to the tests sounds like a good one.

**Comment by ajwagner777** [comment]
Is there any specific way to get the tests to run?  On mac and windows, I get an error:

```
[09:57:10] Starting 'test'...
[09:57:11] Testing index.html
[09:57:11] Can't open '/Users/aaronwagner/Development/js-logger/node_modules/gulp-qunit/node_modules/qunit-phantomjs-runner/runner-json.js'

[09:57:11] 'test' errored after 1.01 s
[09:57:11] Error in plugin 'gulp-qunit'
```

**Comment by jonnyreeves** [comment]
@ajwagner777 hmm, so they should just work on a fresh checkout when you:

```
git clone ...
npm i 
npm test
```

**Pull request merged**
